"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 3.2.18.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-d2*b+(4t3)zn4x_@22yw7_ywc)(7m*f-()^@l(0@2rfoi^dr*x'

# SECURITY WARNING: don't run with debug turned on in production!
# SECURE_CONTENT_TYPE_NOSNIFF = True
# SECURE_BROWSER_XSS_FILTER = True
# SESSION_COOKIE_SECURE = True
# CSRF_COOKIE_SECURE = True
# SECURE_SSL_REDIRECT = True
# SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', 'http://127.0.0.1' , '*']
# CSRF_TRUSTED_ORIGINS  = ['http://*.script39.ru/']
# Application definition

INSTALLED_APPS = [
    'unfold',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'myapp',
    'crispy_forms',
    "crispy_tailwind",
]
UNFOLD = {
    "SITE_TITLE": "<SCRIPT> Admin",
    "SITE_HEADER": "Панель администратора",
    "SITE_URL": "/",  # Ссылка на ваш основной сайт
    "COLORS": {
        "primary": {
            "50": "0 0 0",       # Черный фон
            "100": "0 0 0",       # Дополнительный черный
            "200": "34 34 34",    # Темно-серый для разделов
            "300": "51 51 51",    # Границы или неактивные кнопки
            "400": "0 255 0",     # Зеленый (яркий)
            "500": "0 255 0",     # Основной зеленый
            "600": "0 200 0",     # Темный зеленый
            "700": "0 150 0",     # Очень темный зеленый
            "800": "0 100 0",     # Зеленый акцент
            "900": "0 50 0",      # Границы или эффекты
        },
        "text": {
            "primary": "0 255 0",  # Зеленый текст
            "secondary": "255 255 255",  # Белый текст
            "muted": "128 128 128",  # Серый для подсказок
        },
        "background": {
            "default": "0 0 0",  # Черный фон для админки
            "card": "34 34 34",  # Темно-серый для карточек
        },
    },
    "EXTENSIONS": {
        "colors": True,
        "shadows": True,  # Легкие тени для объемности
    },
    "FONT_FAMILY": "Courier New, monospace",  # Шрифт, похожий на основной стиль
    "FONT_SIZE": {
        "base": "16px",
        "lg": "20px",
        "xl": "24px",
    },
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


CRISPY_TEMPLATE_PACK = "tailwind"
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
STATIC_ROOT = "/var/www/script39_ru_usr/data/www/script39.ru/static/admin"