# Generated by Django 3.2.15 on 2023-08-26 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20230403_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='Email',
        ),
    ]
